# Generated by Django 5.1.2 on 2024-11-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='slmple one-line txet', max_length=100, verbose_name='DESCRIPTION'),
        ),
    ]
